### ISSUE TITLE
Feature Request: Device Name as variable or feedback

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-spotify-remote#11]
Would it be possible to return the name of the active device as either/both a variable and feedback

**Comment by bevanjkay** [comment]
@jmcc94 I have submitted a PR that will make the device name available as a variable. For the feedback would you want to be comparing it to a plain-text inputted device name (can make case-insensitive)?

 PR - #15

**Comment by jmcc94** [comment]
My original thought was to ba able to choose the value to compare from a list of all discovered devices, as of when setting the feedback... but I'm not sure if that would work?

**Comment by bevanjkay** [comment]
Hmm.. @jmcc94 that could be possible. I don't think the module is storing available devices at the moment, but I did notice reference to that in another request. So it could be something to look into in the future.

For now, I think setting the feedback to compare the current device name to a plain-text input could be a good option.

I'm sure you probably understand how variables work in buttons, but having the variable set allows you to output the current device on a button.
