### ISSUE TITLE
New Action - Seek To Position In Currently Playing Track

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-spotify-remote#18]
Would it be possible to create a new action for 'Seek To Position In Currently Playing Track'

This exists in the Spotify API - [https://developer.spotify.com/documentation/web-api/reference/#endpoint-seek-to-position-in-currently-playing-track](url)

[edit] And is exposed in https://github.com/thelinmichael/spotify-web-api-node as spotifyApi.seek(positionMs)

**Comment by bevanjkay** [comment]
@jmcc94 This is implemented in version 1.0.6
