### ISSUE TITLE
Module Request: Spotify control

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion-module-spotify-remote#2]
**Describe the feature**
Control spotify on a local or remote machine
**Is this platform dependent (windows, mac, ..)?**
https://github.com/dronir/SpotifyControl works for mac only

**If documentation is required to implement, do you know where to find it?**
See above project

**Usecases**
Control spotify, usually for BGM purposes.

**Comment by Newyears1978** [comment]
Was this feature ever realized? We use companion at our church and currently we have to use the StreamDecks built in plugin for Spotify which is kind of a pain. We would like to be able to control Spotify from within companion which would allow us to set multiple commands to that button (including spotify)

**Comment by Simber1** [comment]
It is mostly done and functional. it's currently on the lastest bleeding edge builds which you can get from [here](https://bitfocus.io/companion/download/builds/), It will hopefully be included in the next stable build too.

**Comment by Newyears1978** [comment]
> It is mostly done and functional. it's currently on the lastest bleeding edge builds which you can get from [here](https://bitfocus.io/companion/download/builds/), It will hopefully be included in the next stable build too.

Thank you kindly! I am new to using Companion - well I use it but I have not done anything with the software. On the linked page do you have to download each item as modules or are each one full versions including previous changes?

In other words does installing the top file work or would I grab the specific spotify module "Module: Added spotify-remote"

**Comment by Simber1** [comment]
> Edit:
> I did some testing at home using just the web GUI and it worked out fine :) Only thing missing is ability to play a specific playlist (maybe not possible, but I think the built in Spotify module for the StreamDeck has this feature so it must be doable)

It's doable but requires more work since I have to pass the API the URI for the playlist. At some point I'd like to get it done.

**Comment by Newyears1978** [comment]
Very cool - I saw it wasn't in the last update yet - my Tech director is scared to use "unstable" stuff so we're waiting til it's in the official updated. I tested it here at home - worked great :)

Thanks kindly! Oh question - when updating the Companion software do you just install the new version and it auto updates and keeps all the stuff already set up in place? Just want to make sure before we update. I couldn't find any info on updating and also this is all on a Mac, and I am not a Mac user so didn't want to make any assumptions.

**Comment by josephdadams** [comment]
No auto updates. You have to download the latest version any time you want updates.

**Comment by Newyears1978** [comment]
> No auto updates. You have to download the latest version any time you want updates.

Right but what I meant was do you have to resetup everything or does it hold all your buttns and settings when you install the new version?

**Comment by josephdadams** [comment]
Your settings and modules should be retained.

**Comment by Julusian** [comment]
As this module has been in the builds for a while I dont see a reason to keep this issue open
