### ISSUE TITLE
Spotify Module Not Available

### ISSUE THREAD

**Issue by nickgwalkr** [bitfocus/companion-module-spotify-remote#21]
Hello, I can't seem to find the Spotify module in the Companion instances list? Does it have to be installed separately? I believe I'm running the latest verision.
<img width="372" alt="Screen Shot 2021-09-14 at 8 57 35 AM" src="https://user-images.githubusercontent.com/60559796/133261767-24c7cf6e-6e7b-4d15-8a1c-d93257598d33.png">
<img width="889" alt="Screen Shot 2021-09-14 at 8 57 21 AM" src="https://user-images.githubusercontent.com/60559796/133261771-160d9c6d-9657-42e5-9441-bc9153d7957f.png">

**Comment by Julusian** [comment]
You need to be running one of the 2.2 beta builds to use this module
