### ISSUE TITLE
Spotify Module Stopped working

### ISSUE THREAD

**Issue by nickgwalkr** [bitfocus/companion-module-spotify-remote#22]
I've had the companion module setup and running for a few days now and it has worked flawlessly.  It stopped working this afternoon and I can't get it working again.  I have reinstalled companion, re-auth Spotify, and deleted and reinstalled the module. Any ides or suggestions on how to get it working again
<img width="755" alt="Screen Shot 2021-09-30 at 10 10 13 PM" src="https://user-images.githubusercontent.com/60559796/135554968-8c4273ab-ed69-4511-ad5e-793d3f54050b.png">
<img width="579" alt="Screen Shot 2021-09-30 at 10 09 56 PM" src="https://user-images.githubusercontent.com/60559796/135554971-9adf1940-671c-4890-83e1-a5ba535d843e.png">
?

**Comment by bevanjkay** [comment]
Is the active device ID set correctly?

I am still using the module with no issues.

**Comment by nickgwalkr** [comment]
Ahh, yes, I reset active device ID and it is working again. Thanks!
