### ISSUE TITLE
how to get Time Remaining

### ISSUE THREAD

**Issue by nickgwalkr** [bitfocus/companion-module-spotify-remote#23]
Do you have any documentation on getting MM:SS remaining to display as feedback as referenced in the issue below?

I'm running the latest beta build.

https://github.com/bitfocus/companion-module-spotify-remote/pull/19#issuecomment-901503308

**Comment by bevanjkay** [comment]
@nickgwalkr If you click on the `$` icon next to the Spotify module from the `connections` tab you will see a list of available variables.

To get the display you are after put the following as your button text
`$(Spotify:songTimeRemainingMinutes):$(Spotify:songTimeRemainingSeconds)`
