### ISSUE TITLE
How to add the module

### ISSUE THREAD

**Issue by alekitopi** [bitfocus/companion-module-spotify-remote#28]
Hey! I'm new on Companion and I can't find out how to install this module.

I tried to find "modules" on Program Files or AppData/Roaming but nothing. Also, checking the [HELP.md](https://github.com/bitfocus/companion-module-spotify-remote/blob/main/HELP.md) file on this repo, the only setup help is for the Spotify API Keys but not for installing the module.

**Comment by McHauge** [comment]
Go ahead and download the v2.2.0 betas, it's included in there. the only way to add modules your self if you compile companion as a whole by yourself.

**Comment by alekitopi** [comment]
Ohh, okay! tyy ^^
