### ISSUE TITLE
Bug: Cannot read property 'duration_ms' of undefined

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-spotify-remote#3]
From line: https://github.com/bitfocus/companion-module-spotify-remote/blob/0fdb9599bb08e4b81c0d351f000b974554b3fe5a/module.js#L221

This error has been reported in sentry over 152k times in 2 days

**Comment by Simber1** [comment]
Uh, I'll add a check to see if it's playing before trying to set most the vars
