### ISSUE TITLE
Specific Playlist will not play

### ISSUE THREAD

**Issue by ZBLOUNT** [bitfocus/companion-module-spotify-remote#34]
When an instance is made to play a specific playlist and triggered, spotify will clear whatever is currently playing and will not accept any other commands until you play a song or playlist in spotify itself

**Comment by TJNicho** [comment]
Any developments on this?

**Comment by bevanjkay** [comment]
I cannot reproduce this issue. I am constantly using Companion to fire specific playlist, albums and tracks and do not have any issues. 

Can you provide any more details?

**Comment by TJNicho** [comment]
Absolutely! I am using the "Spotify: Start Specific Album / Artist / Playlist action" 

Delay: 0
Type: Playlist
Item ID: https://open.spotify.com/playlist/37i9dQZF1DWZZbwlv3Vmtr?si=6a8c0bfae45a4a23
Action Behavior if Provided Item is Currently Playing: Do Nothing

The button-press cancels out my current Spotify song playing and pulls up the playlist within the Spotify app but the only way I can get it to play is if I go to the app and hit the large green play button within the playlist. 

I have tried using just the ID in the "Item ID" field (ex. 37i9dQZF1DWZZbwlv3Vmtr?si=6a8c0bfae45a4a23) and I get an error within the spotify app.

**Comment by bevanjkay** [comment]
The ID is the second part but you must remove the query string "?si=6a8c0bfae45a4a23"

**Comment by TJNicho** [comment]
@bevanjkay That fixed the issue! Thank you.
