### ISSUE TITLE
$(Spotify:currentAlbumArt) appears to not show correctly on button

### ISSUE THREAD

**Issue by THEENlGMA** [bitfocus/companion-module-spotify-remote#35]
![image](https://user-images.githubusercontent.com/54753846/173246575-ab60dc1f-be33-4ddc-8d97-48db0be35a37.png)
it appears that instead of showing the actual album art it shows the link to the album art, is this a bug or am i doing something wrong?

**Comment by Simber1** [comment]
I believe it's intended to work like that since it's really hard to and or not possible to draw an image to the button with companion.

**Comment by Julusian** [comment]
It is possible and not that hard to draw an image (there is a png64 property in feedbacks), but this module hasnt implemented it yet

**Comment by THEENlGMA** [comment]
[https://github.com/bitfocus/companion/blob/7bf2464b6d46901cac12c91b093aa943dec50d7a/webui/src/Buttons/EditButton/ButtonStyleConfig.jsx](url) This? im assuming, is it possible to add it to my streamdeck now, and if so, how?

**Comment by Julusian** [comment]
Yeah that, but not easily. It will require some code changes in this module to define and implement a new feedback type to do this.
Some work will also need to be done in the module to download the image, maybe resize it and then to encode it correctly and output it from the feedback.

Its fairly straightforward, but not that simple

**Comment by istnv** [comment]
Take a look at the `openweather-rest` module.  I built that one to improve my skills with a REST API.
There is a feedback for 'Current Condition Icon' The module loads these from the online API at start.

**Comment by nacalai** [comment]
Hi there. Any chances of implementing the dynamic background image?

**Comment by trippettjosh** [comment]
Unsure if this is just because I'm using a 3.0 beta of companion but my current work around for this is to use the "Generic: HTTP Requests" Module.
Using the "http: Image from URL" feedback on a button and putting the "$(internal:custom_SpotifyAlbumArt)" variable as the url.
Hope this helps.

**Comment by nacalai** [comment]
> 

Ah damn, nice one! The image from url-feedback is indeed not a feature in 2.4.2. Nice to see it being possible in 3.0. Thanks a lot.

**Comment by Julusian** [comment]
Oh oops, I implemented that in part to support this and forgot to say here...
But yes, this is possible in 3.0

**Comment by trippettjosh** [comment]
Yeah haha, I've had it set that way for a while but was going through the Issues to look for another issue and thought I would just post in case anyone was looking for a solution!

**Comment by Nic0laus** [comment]
Is it a working feature already in 3.0.0? I've downloaded it but I can't seem to find it anywhere :/

**Comment by Nic0laus** [comment]
Okay, so just by using the http requests module, I thought there would be something added next to upload of the png file, thanks a lot ;)
