### ISSUE TITLE
Auth URL not working

### ISSUE THREAD

**Issue by dickmann** [bitfocus/companion-module-spotify-remote#36]
Hi, trying to connect Companion 2.2.2 (latest version) on Mac with Spotify. Easy to build app with Cliend ID and Secret and adding Redirect, but the generated Auth URL is not working. I believe there is a typo error in the generated URL:

i=https://spotauth.github.io/&

If I remove the last "/" it forwards me to the Spotify page to give permission, with the generated original Auth URL I get the error "INVALID_CLIENT: Invalid redirect URI".
When I manually remove the "/" I get a working link, but the generated approval code will not match the Auth URL :-)

Can you fix this please, thank a lot for your support, Michael

**Comment by dickmann** [comment]
Any chance to improve this?

**Comment by dickmann** [comment]
not sure if anything was changed but now everything is working as expecting, closing this issue...

**Comment by Julusian** [comment]
As far as I can tell this is a typo in the documentation, and the url there should also include a trailing slash for it to be ok.
Ive just updated the docs for the next time this module is update in companion
