### ISSUE TITLE
Can't Connect Spotify - Bad Config

### ISSUE THREAD

**Issue by Dwhite2023** [bitfocus/companion-module-spotify-remote#54]
Hi

I'm trying to set up this module, and always says bad config.

I've set up the app following the instructions (and a 2nd time to troubleshoot)
I've added the Client Secret and ID, and redirect link and it gives me the Auth link.
The Auth link works, and gives me an Approval Code but then I don't get an Access Token
I saw in issue #33 They tried a different link, but that didn't fix it.  I've also tried remaking the spotify app, regenerating the client ID/secret it all seems to work, and then I just don't get an access code and the module says 'bad configuration'

Companion version 3.1.1 (latest stable) it is Spotify Premium account, I've tried with both one that is part of a family plan and the owner account of the family plan as well.

**Comment by mickmclean** [comment]
I've just observed the bad config error also.

Had it running with no issues for the last 6 months.

**Comment by srmorris2** [comment]
Can confirm this as well on a previously working config.

**Comment by srmorris2** [comment]
I ended up just making a new API/app on our account and that has fixed our problem.

**Comment by commputethis** [comment]
I ended up making a new app, but after I did, I think the issue is that I don't think the Access Token is probably updating properly.  This is the second time it has happened to me.  The next time it stops working on me, assuming it does, I will try getting a new Approval Code from the Auth URL.

**Comment by joezimjs** [comment]
I have had to use the "Auth Url" to get a new approval code every single week (we use the computer only on weekends). That's all I need to do to get the "Bad Config" error to go away, but having to do it every week is ridiculous.

**Comment by joezimjs** [comment]
I saw this in the [Spotify Developer docs](https://developer.spotify.com/documentation/web-api/concepts/access-token)
 
![Screenshot 2024-08-08 at 8 03 47 PM](https://github.com/user-attachments/assets/6973683d-60fa-462e-8488-a2dfd6ebc62b)

Is this new and is this what is causing the issue?

**Comment by Julusian** [comment]
I've done some fixes that will hopefully stop this from happening. Landing in the betas shortly
