### ISSUE TITLE
Buttons do not work

### ISSUE THREAD

**Issue by dfgnoddr** [bitfocus/companion-module-spotify-remote#55]
All the buttons do not work, play,pause,next,albums etc etc.

The variables show info like artist playtime album etc etc. so the api connection is working.

status shows OK

**Comment by joezimjs** [comment]
Yeah. I just set this up on both my home computers and having the same thing. Do you need Premium to control via API?

**Comment by dfgnoddr** [comment]
Yes you do need premium for the api.

**Comment by joezimjs** [comment]
Yup, looked more closely and found that in the dev docs. Ignore me!

**Comment by dfgnoddr** [comment]
I found the problem. 

You must fill in device id with the number af the device where Spotify plays on. You can find is in the variables in companion.

**Comment by bevanjkay** [comment]
@dfgnoddr I'm glad you found a solution. Can you please close this issue now that it is resolved?
