### ISSUE TITLE
Variables Delay Suddenly

### ISSUE THREAD

**Issue by NewYears1978** [bitfocus/companion-module-spotify-remote#61]
I have been using this plugin for a long time without issue. I have a button that checks the variable to see if it is playing or not and changes the color to green or red.

Always worked fine. However, a couple of weeks ago it started taking 3-5 seconds for this variable update to reflect on the button. The button only has "Play/Stop Spotify" and then the Feedback to look at the playing variable.

The play/stop works instantly it's just the updating of the button which takes about 3-5 seconds.

Any idea? Nothing changed, no updates or anything it just started suddenly.

Using v3.0.0 - want to try to update as maybe something changed somewhere but things usually break when we upgrade so we typically do not upgrade.

**Comment by Julusian** [comment]
I think I've figured this out.
It was trying to parse the responses to requests, and failing (logging an error) resulting in it skipping the extra poll performed immediately after making the change.

Should be fixed now, both the error, and it will always do the poll even if it does error
