### ISSUE TITLE
self.warn is not a function

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion-module-spotify-remote#7]
![image](https://user-images.githubusercontent.com/416667/107103174-f0027d00-681c-11eb-8cc2-287416b9b7cb.png)

We get about 10 000 reports of this error per hour.

**Comment by Simber1** [comment]
I thought I had fixed that issue, I'll fix it when I'm fixing some other bugs in a few days. If you're hitting that line the module wasn't able to refresh your API token for some reason though.

**Comment by haakonnessjoen** [comment]
Oh, great! Sorry about that then! We are just suffering from users using old builds then.
